"""to use gravatar or not

Revision ID: 031e10f41c49
Revises: 6c8f2f001dcc
Create Date: 2023-11-04 14:56:41.379547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031e10f41c49'
down_revision = '6c8f2f001dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_user_gravatar', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('to_user_gravatar')

    # ### end Alembic commands ###
