"""changed the image url to image filename

Revision ID: 4f8a8303b1d2
Revises: a3b45336add7
Create Date: 2023-11-22 22:55:13.872283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f8a8303b1d2'
down_revision = 'a3b45336add7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageName', sa.String(length=128), nullable=True))
        batch_op.drop_column('postImageUrl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postImageUrl', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('imageName')

    # ### end Alembic commands ###
