"""added the the post image url

Revision ID: 6d5ba4c0af79
Revises: 156d52860ece
Create Date: 2023-11-21 22:18:25.346817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5ba4c0af79'
down_revision = '156d52860ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postImageUrl', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('postImageUrl')

    # ### end Alembic commands ###
