"""added the gravatar column

Revision ID: b5e69efd387e
Revises: d03ac593db9d
Create Date: 2023-12-17 14:49:51.764856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e69efd387e'
down_revision = 'd03ac593db9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravatar_picture_url', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_gravatar_picture_url'), ['gravatar_picture_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_gravatar_picture_url'))
        batch_op.drop_column('gravatar_picture_url')

    # ### end Alembic commands ###
