"""added unique post id

Revision ID: d5b3219d88b0
Revises: 4f8a8303b1d2
Create Date: 2023-11-24 16:18:50.289028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b3219d88b0'
down_revision = '4f8a8303b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uniquePostId', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('uniquePostId')

    # ### end Alembic commands ###
