"""corrected to use gravatar or not

Revision ID: e1d4b4dbe092
Revises: 031e10f41c49
Create Date: 2023-11-04 14:58:20.013182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1d4b4dbe092'
down_revision = '031e10f41c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_use_gravatar', sa.Boolean(), nullable=True))
        batch_op.drop_column('to_user_gravatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_user_gravatar', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('to_use_gravatar')

    # ### end Alembic commands ###
